name: sleepy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   

  flutter_svg: ^1.1.5
  provider: ^6.0.4
  cupertino_icons: ^1.0.2
  simple_animations: ^3.1.1
  supercharged: ^2.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^12.0.3
  flutter_native_timezone: ^2.0.0
  flutter_native_splash: ^2.2.13
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  
flutter:

  fonts:      
  - family: Inter
    fonts:
      - asset: fonts/Inter-Thin.ttf
        weight: 100
      - asset: fonts/Inter-ExtraLight.ttf
        weight: 200
      - asset: fonts/Inter-Light.ttf
        weight: 300
      - asset: fonts/Inter-Regular.ttf
        weight: 400
      - asset: fonts/Inter-Medium.ttf
        weight: 500
      - asset: fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: fonts/Inter-Bold.ttf
        weight: 700
      - asset: fonts/Inter-ExtraBold.ttf
        weight: 800
      - asset: fonts/Inter-Black.ttf
        weight: 900

  assets:
    - res/
    - assets/

  uses-material-design: true