/// Flutter icons BottomPanelIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomPanelIcons
///      fonts:
///       - asset: fonts/BottomPanelIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomPanelIcons {
  BottomPanelIcons._();

  static const _kFontFam = 'BottomPanelIcons';
  static const String? _kFontPkg = null;

  static const IconData bed = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
